# Generated by Django 2.0.5 on 2018-08-10 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=4)),
                ('ApplNo', models.CharField(max_length=25, verbose_name='Application Number')),
                ('RMName', models.CharField(max_length=150, verbose_name="RM's Name")),
                ('HRMS', models.CharField(max_length=7, verbose_name='HRMS')),
                ('product', models.CharField(choices=[('HL', 'Home Loan'), ('LAP', 'Loan Against Property'), ('CV', 'Commercial Vehicle Loan'), ('SME', 'SME Loan'), ('Corporate', 'Corporate Loan'), ('Tractor', 'Tractor Loan'), ('AIB', 'Bulk AIB')], max_length=10, verbose_name='Product')),
                ('sanction_amt', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Loan Amount')),
                ('roi', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ROI')),
                ('tenure', models.IntegerField(blank=True, default=60, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tenure')),
                ('utilisation', models.DecimalField(blank=True, decimal_places=2, default=70.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Utilisation')),
                ('ltv', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='LTV')),
                ('rating', models.CharField(blank=True, choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('U', 'Unrated'), ('CM', 'Capital Market'), ('CRE', 'CRE'), ('CRE_RH', 'CRE_RH'), ('RRE', 'RRE'), ('RRP', 'RRP')], default=None, max_length=10, null=True, verbose_name='Rating')),
                ('profee', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('conpay', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sourcing Fee')),
                ('insur', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Insurance Premium')),
                ('other', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Other Income')),
                ('recurr', models.BooleanField(verbose_name='Is Other Income Recurring?')),
                ('psl', models.BooleanField(verbose_name='Priority Sector Lending')),
                ('agri_psl', models.BooleanField(verbose_name='Agri Priority Sector Lending')),
                ('rrp', models.BooleanField(default=False, verbose_name='Is is RRP?')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, default='0.0.0.0', max_length=15)),
            ],
        ),
    ]
